development:
  adapter: postgresql
  encoding: unicode
  database: public
  pool: 5
  username: neutralino1
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: public_test
  pool: 5
  username: neutralino1
  password: 